services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: sql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: workshop_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: